### ISSUE TITLE
add obvious links to end-user documentation (as html and downloadable .doc) to home page

### ISSUE THREAD

**Issue by vviyer** [wsi-cogs/frontend#18]

**Comment by anowlcalledjosh** [comment]
Now available as .docx downloads, linked to from the bottom of every page:

![Image of student portal homepage, with a new "Student Portal Documentation" section at the bottom.](https://user-images.githubusercontent.com/9433472/63174953-e68ac100-c03a-11e9-9fde-2d29714866dc.png)
