### ISSUE TITLE
allow Grad office role to access / run all application UI's and function

### ISSUE THREAD

**Issue by vviyer** [wsi-cogs/frontend#19]

**Comment by anowlcalledjosh** [comment]
What actions can users take? Apart from permissions, what problems might there be with each action being performed by the grad office?

- [ ] Submit a project
  - The project's supervisor is currently the user who submits it (and there's no UI to change a project's supervisor)
- [ ] Edit a project
- [ ] Delete a project
- [ ] Vote for a project
  - The votes are currently attached to the user submitting them
- [ ] Upload a report
- [ ] Mark a report/project
  - Unless the user is the project's supervisor or CoGS marker, the submitted feedback will be stored in the database but not referenced anywhere
  - The name of the marker used in the notification email is the name of the submitting user

There are other UIs for viewing data (e.g. feedback on projects), but that data is also exposed in the exported spreadsheets, unlike these actions (which would currently require poking at the DB by hand if the relevant user was unavailable).

**Comment by anowlcalledjosh** [comment]
summary of discussion:

- key endpoints are project & feedback submission
- less important that grad office can perform other actions

**Comment by anowlcalledjosh** [comment]
Annabel has just suggested that it would be good if the Graduate Office could upload reports on behalf of students.
