### ISSUE TITLE
write handoff docs

### ISSUE THREAD

**Issue by vviyer** [wsi-cogs/frontend#21]
Pitched at developers.
* [x] which libraries / paradigms to read first
* [x] which paradigms are specific to the authors
* [x] exemplary control flow(s): staring from a UI control, the flow of teh code from front-end => back-end => front end.
* [x] schema diagram

**Comment by anowlcalledjosh** [comment]
- https://github.com/wsi-cogs/frontend/wiki/Getting-Started
- https://github.com/wsi-cogs/frontend/wiki/Exemplary-Control-Flow
- https://github.com/wsi-cogs/backend/wiki/Database-Schema

  ![image](https://user-images.githubusercontent.com/9433472/63337318-aed09180-c338-11e9-987b-0608ba0d1490.png)
